apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    purpose: multi-container
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "1000"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
  