apiVersion: v1
kind: Pod
metadata:
  name: annotation-example
  annotations:
    description: "This is an example of a pod with annotations."
    owner: "John Doe"
    imageregistry: "docker.io/library/nginx:latest"