apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: env-demo
    image: nginx
    env:
    - name: COURSE_NAME
      value: "DEvOps with Kubernetes"
    - name: COURSE_DURATION
      value: "3 months"