apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  # These labels are used by the Service to select this Pod.
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80