apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
    purpose: node-port
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  